In [1]:
import numpy as np
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)


[1, 2, 3, 4, 5]
[ 1 11 14 13  3]
[18  2 18  2  6]


In [2]:
li = [i+1 for i in li]
print(li)

[2, 3, 4, 5, 6]


In [3]:
a = a+1  #in case of numpy array
print(a)

[ 2 12 15 14  4]


In [5]:
# c = a+b
c = a+b
print(c)

[20 14 33 16 10]


In [6]:
d = a-b
print(d)

[-16  10  -3  12  -2]


In [7]:
e = a*b
print(e)

[ 36  24 270  28  24]


In [8]:
print(a.sum())
print(a.mean())

47
9.4


In [9]:
print(a.argmin())

0


In [10]:
print(a)

[ 2 12 15 14  4]


In [11]:
print(a.max())
print(a.argmax())

15
2


In [12]:
print(a)
print(b)

[ 2 12 15 14  4]
[18  2 18  2  6]


In [14]:
a > b  #logical expressions

array([False,  True, False,  True, False])

In [15]:
a == b

array([False, False, False, False, False])

In [16]:
a < b

array([ True, False,  True, False,  True])

* logical_or
* logical_and
* logical_not

In [19]:
print(np.logical_or(a,b))  # true for non zero value false for zero
print(np.logical_and(a,b))
print(np.logical_not(a))

[ True  True  True  True  True]
[False False False False False]
[False False False False False]


In [20]:
a[2]= 0
print(np.logical_not(a))

[False False  True False False]


array([ 2, 12,  0, 14,  4])