In [1]:
import numpy as np
li = [1,3,42,34,33]
arr = np.array(li)
print(li)
print(arr)

[1, 3, 42, 34, 33]
[ 1  3 42 34 33]


In [2]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [3]:
print(arr[3])
print(li[3])

print(li[1:4])
print(arr[1:4])

34
34
[3, 42, 34]
[ 3 42 34]


In [4]:
li_2d = [[1,2,3,4],[5,3,2,1],[5,3,23,2],[32,3,2,1]]
arr2d = np.array(li_2d)

print(li_2d)
print(arr2d)

[[1, 2, 3, 4], [5, 3, 2, 1], [5, 3, 23, 2], [32, 3, 2, 1]]
[[ 1  2  3  4]
 [ 5  3  2  1]
 [ 5  3 23  2]
 [32  3  2  1]]


In [5]:
print(arr2d.data)
print(arr2d.shape)
print(arr2d.dtype)
print(arr2d.strides) #(16,4) --> 16 --number of bytes to skip to the next row and 4 bytes to get
# the next element in the same row

(4, 4)
int32
(16, 4)


In [6]:
print(li_2d[2][1])
print(arr2d[2][1])
print(arr2d[2,1]) #[row,column]

3
3
3


In [7]:
print(li_2d[1][:3])
print(arr2d[1,:3])

[5, 3, 2]
[5 3 2]


In [8]:
print(arr2d)

[[ 1  2  3  4]
 [ 5  3  2  1]
 [ 5  3 23  2]
 [32  3  2  1]]


In [9]:
print(li_2d[0:3][2]) # we are not getting 3 2 23

[5, 3, 23, 2]


In [10]:
print(li_2d[0:3][3]) #because in the next step index 3 will be index 2 explanation is below

IndexError: list index out of range

In [11]:
x = li_2d[0:3]
print(x)
            ## this is the explanation
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 3, 2, 1], [5, 3, 23, 2]]
[5, 3, 23, 2]


In [12]:
print(arr2d[0:3,3]) #this workers fine for numpy arrays

[4 1 2]


In [13]:
print(arr2d[2:4,1:3]) #we can't get this in case of normal 2-d list

[[ 3 23]
 [ 3  2]]


In [14]:
print(li_2d[2:4][1:3])

[[32, 3, 2, 1]]


## Numpy is much better

In [15]:
#practice

c =[]
i=0
e=5
j=0
while j<=3:
    a = np.arange(i+1,e+1)
    c.append(a)
    i=i+5
    e=e+5
    j+=1

In [16]:
d =np.array(c)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
print(d[2,0:3])
print(d[1:4,3])
print(d[2:4,])
print(d[1:3,1:3])

[11 12 13]
[ 9 14 19]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]
